### ISSUE TITLE
Another Issue with Flag Sample

### ISSUE THREAD

**Issue by mcanova-usgs** [USGS-R/QWToolbox#76]
The Flag sample feature works with Record Highlighter in the Chargebalance plots. 
Flag sample is misleading in which record number it is highlighting. It might need to be more precise.

Try this:
Make a plot
Use Flag Sample on a point
Note the record number
Highlight that record number with Record Highlighter
Is it the same point?

Works for some points but not others. The issue seems to be more prominent on the far left and right sides of the plot.

Also, use Flag sample and click out in white space. What is the logic behind the record being selected?

**Comment by tmills-usgs** [comment]
The function works by picking whatever sample lies closest to the point clicked on the plot. So whitespace still returns a record number of closest sample point (in theory). This is the issue with the precision as well. It picks the closest point, and sometimes it can not distinguish between two points which are close together.

The way I built the function is a little bit of a hack, and it may never work that great. In which case it will have to  be removed so people are not misled by what they tag. The highlighter works better because it goes off the actual record number and is thus directly linked to the data.

**Comment by tmills-usgs** [comment]
All instances of flag function have now been removed until the function can be improved. To much risk of misinterpreting data.
